version: '3.4'


services:
  go-server:
    image: golang
    container_name: "ztrback"
    build: ./
    command: ./app
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://root:root@postgresdb:5432/ztrback-db
    ports:
      - 3000:3000
    depends_on:
      - postgresdb


  postgresdb:
    image: postgres:latest
    container_name: "ztrback-db"
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ztrback-db
      - POSTGRES_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=ztrback-db
      - PORT=5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./.data/db:/data/db
    ports:
      - 5432:5432