version: '3.4'


services:
  go-server:
    image: dockerhub.timeweb.cloud/library/golang
    container_name: "ztrback"
    build: ./
    command: ./app
    env_file: .env
    environment:
      - DATABASE_URL=postgres://root:root@postgresdb:5432/root?sslmode=disable
    ports:
      - 3000:3000
    depends_on:
      - postgresdb


  postgresdb:
    image: dockerhub.timeweb.cloud/library/postgres:15.6
    container_name: "ztrback-db"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./.data/db:/data/db
    ports:
      - 5432:5432